/**
 * ABI Management Command (TASK-009)
 *
 * Export, import, and list contract ABIs
 */

import chalk from "chalk";
import ora from "ora";
import fs from "fs/promises";
import path from "path";
import {
  printHeader,
  printKeyValue,
  printSuccess,
  printError,
  printWarning,
  printInfo,
  newLine,
} from "../utils/output.js";

interface AbiOptions {
  output?: string;
  format?: string;
}

/**
 * Find all contract artifacts in the project
 */
async function findArtifacts(): Promise<
  { name: string; path: string; source: string }[]
> {
  const artifacts: { name: string; path: string; source: string }[] = [];

  // Check Hardhat artifacts
  const hardhatPath = path.join(process.cwd(), "artifacts", "contracts");
  try {
    const dirs = await fs.readdir(hardhatPath);
    for (const dir of dirs) {
      if (dir.endsWith(".sol")) {
        const contractDir = path.join(hardhatPath, dir);
        const files = await fs.readdir(contractDir);
        for (const file of files) {
          if (file.endsWith(".json") && !file.endsWith(".dbg.json")) {
            artifacts.push({
              name: file.replace(".json", ""),
              path: path.join(contractDir, file),
              source: "hardhat",
            });
          }
        }
      }
    }
  } catch {
    // No Hardhat artifacts
  }

  // Check Foundry out
  const foundryPath = path.join(process.cwd(), "out");
  try {
    const dirs = await fs.readdir(foundryPath);
    for (const dir of dirs) {
      if (dir.endsWith(".sol")) {
        const contractDir = path.join(foundryPath, dir);
        const files = await fs.readdir(contractDir);
        for (const file of files) {
          if (file.endsWith(".json")) {
            artifacts.push({
              name: file.replace(".json", ""),
              path: path.join(contractDir, file),
              source: "foundry",
            });
          }
        }
      }
    }
  } catch {
    // No Foundry artifacts
  }

  // Check abis directory
  const abisPath = path.join(process.cwd(), "abis");
  try {
    const files = await fs.readdir(abisPath);
    for (const file of files) {
      if (file.endsWith(".json")) {
        artifacts.push({
          name: file.replace(".json", ""),
          path: path.join(abisPath, file),
          source: "imported",
        });
      }
    }
  } catch {
    // No abis directory
  }

  return artifacts;
}

/**
 * Load ABI from artifact file
 */
async function loadArtifact(
  artifactPath: string
): Promise<{ abi: any[]; bytecode?: string }> {
  const content = await fs.readFile(artifactPath, "utf-8");
  const parsed = JSON.parse(content);

  // Handle different artifact formats
  if (Array.isArray(parsed)) {
    return { abi: parsed };
  }

  return {
    abi: parsed.abi || parsed,
    bytecode: parsed.bytecode || parsed.deployedBytecode,
  };
}

/**
 * Generate TypeScript types from ABI
 */
function generateTypes(contractName: string, abi: any[]): string {
  const lines: string[] = [
    `// Auto-generated TypeScript types for ${contractName}`,
    `// Generated by: selendra abi export ${contractName} --format ts`,
    "",
    `export const ${contractName}ABI = ${JSON.stringify(
      abi,
      null,
      2
    )} as const;`,
    "",
    `export type ${contractName}ABI = typeof ${contractName}ABI;`,
    "",
  ];

  // Extract function names for type hints
  const functions = abi.filter((item) => item.type === "function");
  if (functions.length > 0) {
    lines.push(`// Function names available on this contract:`);
    lines.push(
      `export type ${contractName}Functions = ${functions
        .map((f) => `'${f.name}'`)
        .join(" | ")};`
    );
    lines.push("");
  }

  // Extract event names
  const events = abi.filter((item) => item.type === "event");
  if (events.length > 0) {
    lines.push(`// Event names emitted by this contract:`);
    lines.push(
      `export type ${contractName}Events = ${events
        .map((e) => `'${e.name}'`)
        .join(" | ")};`
    );
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Export ABI command
 */
async function exportAbi(contractName: string, options: AbiOptions) {
  printHeader("Export Contract ABI");

  const spinner = ora("Finding contract artifact...").start();

  try {
    const artifacts = await findArtifacts();
    const artifact = artifacts.find(
      (a) => a.name.toLowerCase() === contractName.toLowerCase()
    );

    if (!artifact) {
      spinner.fail(`Contract '${contractName}' not found`);
      newLine();
      printInfo("Available contracts:");
      for (const a of artifacts) {
        console.log(chalk.gray(`  • ${a.name} (${a.source})`));
      }
      return;
    }

    spinner.text = "Loading ABI...";
    const { abi, bytecode } = await loadArtifact(artifact.path);

    const format = options.format || "json";
    const outputDir = options.output || path.join(process.cwd(), "abis");

    // Ensure output directory exists
    await fs.mkdir(outputDir, { recursive: true });

    let outputPath: string;
    let content: string;

    if (format === "ts" || format === "typescript") {
      outputPath = path.join(outputDir, `${contractName}.ts`);
      content = generateTypes(contractName, abi);
    } else {
      outputPath = path.join(outputDir, `${contractName}.json`);
      content = JSON.stringify(abi, null, 2);
    }

    await fs.writeFile(outputPath, content);
    spinner.succeed("ABI exported successfully");

    newLine();
    printHeader("Export Details");
    printKeyValue("Contract:", contractName);
    printKeyValue("Source:", artifact.source);
    printKeyValue("Format:", format);
    printKeyValue("Output:", outputPath);
    printKeyValue(
      "Functions:",
      abi.filter((i) => i.type === "function").length.toString()
    );
    printKeyValue(
      "Events:",
      abi.filter((i) => i.type === "event").length.toString()
    );

    if (bytecode) {
      printKeyValue("Bytecode:", "included");
    }

    newLine();
    printSuccess(`ABI saved to ${outputPath}`);
    newLine();
  } catch (error: any) {
    spinner.fail("Export failed");
    printError(error.message);
  }
}

/**
 * Import ABI command
 */
async function importAbi(filePath: string, options: AbiOptions) {
  printHeader("Import Contract ABI");

  const spinner = ora("Loading ABI file...").start();

  try {
    const content = await fs.readFile(filePath, "utf-8");
    const parsed = JSON.parse(content);

    // Determine if it's raw ABI or artifact
    const abi = Array.isArray(parsed) ? parsed : parsed.abi;

    if (!Array.isArray(abi)) {
      throw new Error("Invalid ABI format - expected array");
    }

    // Determine contract name from filename
    const contractName = path
      .basename(filePath)
      .replace(".json", "")
      .replace(".abi", "");

    // Save to abis directory
    const outputDir = options.output || path.join(process.cwd(), "abis");
    await fs.mkdir(outputDir, { recursive: true });

    const outputPath = path.join(outputDir, `${contractName}.json`);
    await fs.writeFile(outputPath, JSON.stringify(abi, null, 2));

    spinner.succeed("ABI imported successfully");

    newLine();
    printHeader("Import Details");
    printKeyValue("Contract:", contractName);
    printKeyValue("Source:", filePath);
    printKeyValue("Output:", outputPath);
    printKeyValue(
      "Functions:",
      abi.filter((i: any) => i.type === "function").length.toString()
    );
    printKeyValue(
      "Events:",
      abi.filter((i: any) => i.type === "event").length.toString()
    );
    newLine();

    printSuccess(`ABI saved to ${outputPath}`);
    newLine();
  } catch (error: any) {
    spinner.fail("Import failed");
    printError(error.message);
  }
}

/**
 * List available ABIs
 */
async function listAbis() {
  printHeader("Available Contract ABIs");

  const spinner = ora("Scanning for artifacts...").start();

  try {
    const artifacts = await findArtifacts();

    spinner.succeed(`Found ${artifacts.length} contracts`);
    newLine();

    if (artifacts.length === 0) {
      printWarning("No contract artifacts found");
      newLine();
      printInfo("Compile contracts first:");
      console.log(chalk.gray("  selendra compile"));
      newLine();
      printInfo("Or import an ABI:");
      console.log(chalk.gray("  selendra abi import ./path/to/abi.json"));
      return;
    }

    // Group by source
    const bySource: Record<string, typeof artifacts> = {};
    for (const artifact of artifacts) {
      if (!bySource[artifact.source]) {
        bySource[artifact.source] = [];
      }
      bySource[artifact.source].push(artifact);
    }

    for (const [source, items] of Object.entries(bySource)) {
      console.log(chalk.bold.cyan(`\n${source.toUpperCase()}:`));
      for (const item of items) {
        try {
          const { abi } = await loadArtifact(item.path);
          const fnCount = abi.filter((i) => i.type === "function").length;
          const evCount = abi.filter((i) => i.type === "event").length;
          console.log(
            chalk.white(`  ${item.name}`) +
              chalk.gray(` (${fnCount} functions, ${evCount} events)`)
          );
        } catch {
          console.log(
            chalk.white(`  ${item.name}`) + chalk.gray(" (error loading)")
          );
        }
      }
    }

    newLine();
    printInfo("Export an ABI:");
    console.log(chalk.gray("  selendra abi export <contract-name>"));
    console.log(
      chalk.gray("  selendra abi export <contract-name> --format ts")
    );
    newLine();
  } catch (error: any) {
    spinner.fail("Failed to list ABIs");
    printError(error.message);
  }
}

export async function abiCommand(
  action: string,
  target?: string,
  options: AbiOptions = {}
) {
  switch (action) {
    case "export":
      if (!target) {
        console.error(chalk.red("Contract name required"));
        console.log(chalk.gray("Usage: selendra abi export <contract-name>"));
        process.exit(1);
      }
      await exportAbi(target, options);
      break;

    case "import":
      if (!target) {
        console.error(chalk.red("File path required"));
        console.log(chalk.gray("Usage: selendra abi import <file-path>"));
        process.exit(1);
      }
      await importAbi(target, options);
      break;

    case "list":
      await listAbis();
      break;

    default:
      await listAbis();
  }
}

/**
 * Subcommand handlers for Commander.js
 */
export const abiSubcommands = {
  export: async (contract: string, options: AbiOptions) => {
    await exportAbi(contract, options);
  },
  import: async (
    source: string,
    options: AbiOptions & { name?: string; network?: string }
  ) => {
    await importAbi(source, options);
  },
  list: async () => {
    await listAbis();
  },
  types: async (abiPath: string, options: AbiOptions) => {
    // Generate TypeScript types from ABI
    const content = await fs.readFile(abiPath, "utf-8");
    const parsed = JSON.parse(content);
    const abi = Array.isArray(parsed) ? parsed : parsed.abi;
    const contractName = path.basename(abiPath).replace(".json", "");
    const types = generateTypes(contractName, abi);

    const outputPath = options.output || `${contractName}.types.ts`;
    await fs.writeFile(outputPath, types);
    printSuccess(`TypeScript types saved to ${outputPath}`);
  },
};
